version: "3.7"

services:
  discount_database:
    image: postgres
    volumes:
      - pg_discount_data:/var/lib/postgresql/data/
    env_file:
      - ./discount_service/.env.database
    ports:
      - 5432:5432

  eureka_server:
    build: ../eureka-server
    ports:
      - 8761:8761

  address_service:
    build: ../address-service
    restart: always
    ports:
      - 8001:8000
    depends_on:
      - discount_database
      - eureka_server
    env_file:
      - ./address_service/.env

  partners_service:
    build: ../partners-service
    restart: always
    ports:
      - 8002:8000
    depends_on:
      - discount_database
      - address_service
      - eureka_server
    env_file:
      - ./partners_service/.env

  items_service:
    build: ../items-service
    restart: always
    ports:
      - 8003:8000
    depends_on:
      - discount_database
      - eureka_server
      - address_service
      - partners_service
    env_file:
      - ./items_service/.env

  orders_service:
    build: ../orders-service
    restart: always
    ports:
      - 8004:8000
    depends_on:
      - discount_database
      - eureka_server
      - address_service
      - partners_service
      - items_service
    env_file:
      - ./orders_service/.env

  frontend:
    build: ../discounts-frontend
    ports:
      - 8005:80
    depends_on:
      - address_service
      - partners_service
      - items_service
      - orders_service
    env_file:
      - ./frontend/.env

  web:
    build: ./web_server
    ports:
      - 80:80
      - 443:443
    depends_on:
      - address_service
      - partners_service
      - items_service
      - orders_service
    links:
      - "address_service:address_service"
      - "partners_service:partners_service"
      - "items_service:items_service"
      - "orders_service:orders_service"


volumes:
  pg_discount_data: